/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Dao.ConexaoBD;
import Dao.ProfDAO;
import Modelo.ModeloProf;
import Modelo.ModeloTabela;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @Matheus
 */
public class CadastroProf extends javax.swing.JFrame {
     ConexaoBD conexao = new ConexaoBD();
     ModeloProf modp = new ModeloProf();
     ProfDAO  controle = new ProfDAO();
     int flag = 0;
    
    
    public CadastroProf() {
        this.setTitle(" CADASTRO DE PROFESSOR ");
        this.setResizable(false);
        initComponents();
        preencherTabela("select * from professores order by nomeProf");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextFIdProfessor = new javax.swing.JTextField();
        jTextFNome = new javax.swing.JTextField();
        jTextFEmail = new javax.swing.JTextField();
        jTextFCurso = new javax.swing.JTextField();
        jTextFHoraAula = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jbNovo = new javax.swing.JButton();
        jbSalvar = new javax.swing.JButton();
        jbExcluir = new javax.swing.JButton();
        jbEditar = new javax.swing.JButton();
        jbPesquisar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTableProfessor = new javax.swing.JTable();
        jTextFPesquisa = new javax.swing.JTextField();
        jbCancelar = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("CADASTRO DE PROFESSOR"));

        jTextFIdProfessor.setEditable(false);
        jTextFIdProfessor.setEnabled(false);

        jTextFNome.setEnabled(false);
        jTextFNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFNomeActionPerformed(evt);
            }
        });

        jTextFEmail.setEnabled(false);

        jTextFCurso.setEnabled(false);

        jTextFHoraAula.setEnabled(false);

        jLabel1.setText("Codigo:");

        jLabel2.setText("Nome:");

        jLabel3.setText("Email:");

        jLabel4.setText("Hora Aula:");

        jLabel5.setText("Curso Ministrado");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jTextFEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(0, 132, Short.MAX_VALUE))
                            .addComponent(jTextFCurso))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextFIdProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(51, 51, 51)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jTextFNome))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFHoraAula, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFHoraAula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFIdProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jbNovo.setText("Novo");
        jbNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNovoActionPerformed(evt);
            }
        });

        jbSalvar.setText("Salvar");
        jbSalvar.setEnabled(false);
        jbSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarActionPerformed(evt);
            }
        });

        jbExcluir.setText("Excluir");
        jbExcluir.setEnabled(false);
        jbExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluirActionPerformed(evt);
            }
        });

        jbEditar.setText("Editar");
        jbEditar.setEnabled(false);
        jbEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEditarActionPerformed(evt);
            }
        });

        jbPesquisar.setText("Pesquisar");
        jbPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPesquisarActionPerformed(evt);
            }
        });

        JTableProfessor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        JTableProfessor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTableProfessorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JTableProfessor);

        jbCancelar.setText("Cancelar");
        jbCancelar.setEnabled(false);
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 33, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jTextFPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbNovo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE))
                        .addGap(14, 14, 14)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbNovo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbExcluir))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbPesquisar)
                    .addComponent(jTextFPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(718, 480));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFNomeActionPerformed

    private void jbNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNovoActionPerformed
        flag = 1;
        jTextFNome.setEnabled(true);
        jTextFEmail.setEnabled(true);
        jTextFHoraAula.setEnabled(true);
        jTextFCurso.setEnabled(true);
        jbSalvar.setEnabled(true);
        BotaoNovo();
        
    }//GEN-LAST:event_jbNovoActionPerformed

    private void jbSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarActionPerformed
         if(jTextFNome.getText().isEmpty()){
          JOptionPane.showMessageDialog(null, "Preencha o campo NOME para continuar");
          jTextFNome.requestFocus();
          }else{
                if(jTextFEmail.getText().isEmpty()){
                   JOptionPane.showMessageDialog(null, "Preencha o campo EMAIL para continuar");
                   jTextFEmail.requestFocus();
                  }else{
                        if(jTextFHoraAula.getText().isEmpty()){
                           JOptionPane.showMessageDialog(null, "Preencha o campo VALOR HORA para continuar");
                           jTextFHoraAula.requestFocus();
                          }else {
                                 if(jTextFCurso.getText().isEmpty()){
                                    JOptionPane.showMessageDialog(null, "Preencha o campo FORMAÇÃO  para continuar");
                                    jTextFCurso.requestFocus();
                                    
                                   }else{
                                         
        if(flag ==1)
        {
        modp.setNome(jTextFNome.getText());
        modp.setEmail(jTextFEmail.getText());
        modp.setValorhora(jTextFHoraAula.getText());
        modp.setFormacao(jTextFCurso.getText());
        controle.salvar(modp);
        jTextFIdProfessor.setText("");
        jTextFNome.setText("");
        jTextFEmail.setText("");
        jTextFHoraAula.setText("");
        jTextFCurso.setText("");
        jTextFNome.setEnabled(false);
        jTextFEmail.setEnabled(false);
        jTextFHoraAula.setEnabled(false);
        jTextFCurso.setEnabled(false);
        BotaoSalvarflag1();
        preencherTabela("select * from professores order by nomeProf");
        
        } else{
            modp.setNome(jTextFNome.getText());
            modp.setEmail(jTextFEmail.getText());
            modp.setValorhora(jTextFHoraAula.getText());
            modp.setFormacao(jTextFCurso.getText());
            controle.Editar(modp);
            jTextFIdProfessor.setText("");
            jTextFNome.setText("");
            jTextFEmail.setText("");
            jTextFHoraAula.setText("");
            jTextFCurso.setText("");
            jTextFNome.setEnabled(false);
            jTextFEmail.setEnabled(false);
            jTextFHoraAula.setEnabled(false);
            jTextFCurso.setEnabled(false);
            BotaoSalvarflag1();
            preencherTabela("select * from professores order by nomeProf");
            }  
                                        }
                                }
                           
                       }
               }
        
       
    }//GEN-LAST:event_jbSalvarActionPerformed

    private void jbExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluirActionPerformed
          int resposta = 0;
          resposta = JOptionPane.showConfirmDialog(rootPane,"Deseja relmente excluir o Professor");
          if(resposta == JOptionPane.YES_OPTION)
              modp.setIdprofessor(Integer.valueOf(jTextFIdProfessor.getText()));
              controle.Excluir(modp);
              jTextFIdProfessor.setText("");
              jTextFNome.setText("");
              jTextFEmail.setText("");
              jTextFHoraAula.setText("");
              jTextFCurso.setText("");
              BotaoExcluir();
              preencherTabela("select * from professores order by nomeProf");
    }//GEN-LAST:event_jbExcluirActionPerformed

    private void jbEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEditarActionPerformed
                flag = 2;       
                jTextFNome.setEnabled(true);
                jTextFEmail.setEnabled(true);
                jTextFHoraAula.setEnabled(true);
                jTextFCurso.setEnabled(true);
                BotaoEditar();
    }//GEN-LAST:event_jbEditarActionPerformed

    private void jbPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPesquisarActionPerformed
               modp.setPesquisar(jTextFPesquisa.getText());
               ModeloProf modelo = controle.BuscarProf(modp);
               
               jTextFIdProfessor.setText(String.valueOf(modelo.getIdprofessor()));
               jTextFNome.setText(modelo.getNomeprof());
               jTextFEmail.setText(modelo.getEmailprof());
               jTextFHoraAula.setText(modelo.getValorhora());
               jTextFCurso.setText(modelo.getFormacao());
               jbCancelar.setEnabled(false);
               preencherTabela("select * from professores where nomeProf like'%"+modp.getPesquisar()+"%'");
    }//GEN-LAST:event_jbPesquisarActionPerformed

    private void JTableProfessorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTableProfessorMouseClicked
        String nomeProf = ""+JTableProfessor.getValueAt(JTableProfessor.getSelectedRow(), 1);
        conexao.conexao();
        conexao.executaSql("select * from professores where nomeProf = '"+nomeProf+"'");
        
         try {
             conexao.result.first();
             jTextFIdProfessor.setText(String.valueOf(conexao.result.getInt("idProf")));
             jTextFNome.setText(conexao.result.getString("nomeProf"));
             jTextFEmail.setText(conexao.result.getString("emailProf"));
             jTextFHoraAula.setText(conexao.result.getString("valorHora"));
             jTextFCurso.setText(conexao.result.getString("formacao"));
         } catch (SQLException ex) {
             JOptionPane.showMessageDialog(null,"Erro ao selecionar dados"+ex); 
         }
        conexao.desconecta();
        BotaoPesquisar();
    }//GEN-LAST:event_JTableProfessorMouseClicked

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
          
        jTextFNome.setEnabled(!true);
        jTextFEmail.setEnabled(!true);
        jTextFHoraAula.setEnabled(!true);
        jTextFCurso.setEnabled(!true);
        
        jTextFNome.setText("");
        jTextFEmail.setText("");
        jTextFHoraAula.setText("");
        jTextFCurso.setText("");
        jTextFIdProfessor.setText("");
        BotaoCancelar();
           
    }//GEN-LAST:event_jbCancelarActionPerformed
    public void preencherTabela(String sql){
        ArrayList dados = new ArrayList();
        String [] colunas = new String[]{"ID","Nome","Email","Valor Hora", "Formação"};
        conexao.conexao();
        conexao.executaSql(sql);
        
         try {
             conexao.result.first();
             do{
                dados.add(new Object[]{conexao.result.getInt("idProf"),conexao.result.getString("nomeProf"),conexao.result.getString("emailProf"), conexao.result.getString("valorHora"), conexao.result.getString("formacao")});  
             }while(conexao.result.next());
         } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,"Digite outro nome");
         }
         ModeloTabela modelo = new ModeloTabela(dados, colunas);
         
         JTableProfessor.setModel(modelo);
         JTableProfessor.getColumnModel().getColumn(0).setPreferredWidth(35);
         JTableProfessor.getColumnModel().getColumn(0).setResizable(false);
         JTableProfessor.getColumnModel().getColumn(1).setPreferredWidth(210);
         JTableProfessor.getColumnModel().getColumn(1).setResizable(false);
         JTableProfessor.getColumnModel().getColumn(2).setPreferredWidth(210);
         JTableProfessor.getColumnModel().getColumn(2).setResizable(false);
         JTableProfessor.getColumnModel().getColumn(3).setPreferredWidth(70);
         JTableProfessor.getColumnModel().getColumn(3).setResizable(false);
         JTableProfessor.getColumnModel().getColumn(4).setPreferredWidth(113);
         JTableProfessor.getColumnModel().getColumn(4).setResizable(false);
         JTableProfessor.getTableHeader().setReorderingAllowed(false);
         JTableProfessor.setAutoResizeMode(JTableProfessor.AUTO_RESIZE_OFF);
         JTableProfessor.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
         conexao.desconecta();
         
         
    }

//Declaração dos metodos para ativar e desativar os botões do formulario
    public void BotaoNovo()
    {
       jbSalvar.setEnabled(true);
       jbCancelar.setEnabled(true);
    }
    
       public void BotaoSalvarflag1()
    {
      jbSalvar.setEnabled(false);
      jbCancelar.setEnabled(false);
      jbEditar.setEnabled(false);
      jbExcluir.setEnabled(false);
    }
       public void BotaoSalvarflag2()
    {
      jbSalvar.setEnabled(false);
      jbNovo.setEnabled(true);
      jbCancelar.setEnabled(false);
    }
    
       public void BotaoEditar()
    {
       jbSalvar.setEnabled(true);
       jbNovo.setEnabled(true);
       jbCancelar.setEnabled(true);      
       jbEditar.setEnabled(false);
       jbNovo.setEnabled(false);
       jbExcluir.setEnabled(false);
    }
    
       public void BotaoCancelar()
    {
       jbSalvar.setEnabled(!true);
       jbCancelar.setEnabled(!true);
       jbNovo.setEnabled(true);
       jbEditar.setEnabled(false);
       jbExcluir.setEnabled(false);
    }
       
       public void BotaoExcluir()
    {
       
       jbEditar.setEnabled(false);
       jbNovo.setEnabled(true);
       jbCancelar.setEnabled(!true);
       jbExcluir.setEnabled(false);
    }
       
        public void BotaoPesquisar()
    {
      jbCancelar.setEnabled(true);
      jbEditar.setEnabled(true);
      jbExcluir.setEnabled(true);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroProf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroProf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroProf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroProf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroProf().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTableProfessor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFCurso;
    private javax.swing.JTextField jTextFEmail;
    private javax.swing.JTextField jTextFHoraAula;
    private javax.swing.JTextField jTextFIdProfessor;
    private javax.swing.JTextField jTextFNome;
    private javax.swing.JTextField jTextFPesquisa;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbEditar;
    private javax.swing.JButton jbExcluir;
    private javax.swing.JButton jbNovo;
    private javax.swing.JButton jbPesquisar;
    private javax.swing.JButton jbSalvar;
    // End of variables declaration//GEN-END:variables
}
