/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Dao.ConexaoBD;
import Modelo.ModeloTabela;
import java.sql.Date;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Rogerio
 */
public class Matricula extends javax.swing.JFrame {
       ConexaoBD conexao = new ConexaoBD();
       int flag =0;
    /**
     * Creates new form Matricula
     */
    public Matricula() {
        initComponents();
        editarDataMatricua();
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbEditar = new javax.swing.JButton();
        jbExcluir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTableBuscar = new javax.swing.JTable();
        jbCancelar = new javax.swing.JButton();
        jLabelTitulo = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        JTableMatriculados = new javax.swing.JTable();
        jTextFieldInicioCurso = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldNomeAluno = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldNasc = new javax.swing.JTextField();
        jbBuscarAluno = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldDataMatricula = new javax.swing.JTextField();
        jTextFieldNumMatricula = new javax.swing.JTextField();
        jTextFieldNomeTurma = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldCurso = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jbBuscarTurma = new javax.swing.JButton();
        jTextFieldIdTurmas = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldProfessor = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jbSalvar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jbEditar.setText("Editar Matricula");
        jbEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEditarActionPerformed(evt);
            }
        });

        jbExcluir.setText("Excluir Matricula");
        jbExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluirActionPerformed(evt);
            }
        });

        JTableBuscar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        JTableBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTableBuscarMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JTableBuscar);

        jbCancelar.setText("Cancelar Matricula");
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        jLabelTitulo.setBackground(new java.awt.Color(0, 204, 0));
        jLabelTitulo.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(0, 153, 0));
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setText("FORMULARIO DE MATRÍCULA");

        JTableMatriculados.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Matriculados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP));
        JTableMatriculados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        JTableMatriculados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTableMatriculadosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(JTableMatriculados);

        jTextFieldInicioCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldInicioCursoActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel10.setText("Nome Aluno");

        jLabel11.setText("Data Nasc");

        jbBuscarAluno.setText("Buscar");
        jbBuscarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarAlunoActionPerformed(evt);
            }
        });

        jLabel3.setText("Data Matricula");

        jTextFieldNumMatricula.setEnabled(false);

        jLabel1.setText("Curso:");

        jLabel2.setText("Professor:");

        jbBuscarTurma.setText("Buscar");
        jbBuscarTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarTurmaActionPerformed(evt);
            }
        });

        jTextFieldIdTurmas.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTextFieldIdTurmas.setEnabled(false);

        jLabel7.setText("Turma:");

        jLabel4.setText("Nº  Matricula");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addGap(26, 26, 26)
                        .addComponent(jTextFieldNomeTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbBuscarTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldCurso))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldNomeAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbBuscarAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11)
                        .addGap(10, 10, 10)
                        .addComponent(jTextFieldNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextFieldDataMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldNumMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 8, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldProfessor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldIdTurmas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextFieldNomeAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jTextFieldNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbBuscarAluno)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldDataMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNumMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldIdTurmas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(jTextFieldCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(jTextFieldNomeTurma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbBuscarTurma))))
        );

        jLabel12.setText("Inicio do Curso");

        jbSalvar.setText("Matricular Aluno");
        jbSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jbCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jbExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jbEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(213, 213, 213))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 960, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 973, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(18, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jbSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(82, 82, 82))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldInicioCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jTextFieldInicioCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbSalvar)
                        .addGap(31, 31, 31)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCancelar)
                    .addComponent(jbExcluir)
                    .addComponent(jbEditar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
     public void editarDataMatricua(){
         if(flag == 4){
        jTextFieldDataMatricula.setText("dd/MM/yyyy");
     }else if(flag == 1 ||flag == 2){
           jTextFieldDataMatricula.setText(new SimpleDateFormat("dd/MM/yyyy").format(new Date(System.currentTimeMillis())));
     }else{jTextFieldDataMatricula.setText(new SimpleDateFormat("dd/MM/yyyy").format(new Date(System.currentTimeMillis())));}
     }
    private void jbEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEditarActionPerformed
             flag=4;
             editarDataMatricua();
    }//GEN-LAST:event_jbEditarActionPerformed

    private void jbExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluirActionPerformed
        
    }//GEN-LAST:event_jbExcluirActionPerformed

    private void JTableBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTableBuscarMouseClicked
       if(flag == 1) {
           conexao.conexao();
         
           try {
          String nomeAluno = ""+JTableBuscar.getValueAt(JTableBuscar.getSelectedRow(),1);
          conexao.executaSql("select * from alunos where nomeAluno = '"+nomeAluno+"'");
               conexao.result.first();
               Date nasc_aluno = conexao.result.getDate("nascAluno");
               jTextFieldNomeAluno.setText(nomeAluno);
               jTextFieldNasc.setText(String.valueOf(nasc_aluno));
               conexao.desconecta();
           } catch (SQLException ex) {
               JOptionPane.showMessageDialog(null,"Aluno não encontrado"+ ex);
           } 
            }else{
           
           conexao.conexao();
           try{
           String nomeTurma=""+JTableBuscar.getValueAt(JTableBuscar.getSelectedRow(),1);
           conexao.executaSql("select * from turmas where nomeTurmas = '"+nomeTurma+"'");
               conexao.result.first();
               Date datainicio = conexao.result.getDate("dataInicio");
               jTextFieldNomeTurma.setText(nomeTurma);
               jTextFieldInicioCurso.setText(String.valueOf(datainicio));
               conexao.desconecta();
           } catch (SQLException ex) {
               JOptionPane.showMessageDialog(null,"Turma  não encontrado"+ ex);
           }
            conexao.conexao();
           try{
               
           String nomeTurma=""+JTableBuscar.getValueAt(JTableBuscar.getSelectedRow(),1);
           conexao.executaSql("select * from turmas where nomeTurmas = '"+nomeTurma+"'");
               conexao.result.first();
               Date datainicio = conexao.result.getDate("dataInicio");
               jTextFieldNomeTurma.setText(nomeTurma);
               jTextFieldInicioCurso.setText(String.valueOf(datainicio));
                       
               ConexaoBD conexPesquisar = new ConexaoBD();
               conexPesquisar.conexao();
               conexPesquisar.executaSql("select * from professores where idProf = "+conexao.result.getInt("tur_idProf"));
               conexPesquisar.result.first();
               jTextFieldProfessor.setText(conexPesquisar.result.getString("nomeProf"));
               conexPesquisar.desconecta();
               
               conexPesquisar.conexao();
               conexPesquisar.executaSql("select * from cursos where idCurso = "+conexao.result.getInt("tur_idCurso"));
               conexPesquisar.result.first();
               jTextFieldCurso.setText(conexPesquisar.result.getString("nomeCurso"));
               conexPesquisar.desconecta();
            
           } catch (SQLException ex) {
               JOptionPane.showMessageDialog(null,"Turma  não encontrado"+ ex);
               }
           conexao.desconecta(); 
       } 
        
    }//GEN-LAST:event_JTableBuscarMouseClicked

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
  
    }//GEN-LAST:event_jbCancelarActionPerformed

    private void jbSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarActionPerformed
       
       
    }//GEN-LAST:event_jbSalvarActionPerformed

    private void JTableMatriculadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTableMatriculadosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_JTableMatriculadosMouseClicked

    private void jbBuscarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarAlunoActionPerformed
        flag=1;
        editarDataMatricua();
        preencherTabelaAluno("select * from alunos where nomeAluno like'%"+jTextFieldNomeAluno.getText()+"%'");
    }//GEN-LAST:event_jbBuscarAlunoActionPerformed

    private void jbBuscarTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarTurmaActionPerformed
       flag=2;
       editarDataMatricua();
        preencherTabelaTurmas("select * from turmas where nomeTurmaS like'%"+jTextFieldNomeTurma.getText()+"%'");
    
    }//GEN-LAST:event_jbBuscarTurmaActionPerformed

    private void jTextFieldInicioCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldInicioCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldInicioCursoActionPerformed
    public void preencherTabelaAluno(String sql){
             ArrayList dados = new ArrayList();
        String [] colunas = new String[]{"Codigo", "Nome", "Nasc Aluno"};
        conexao.conexao();
        conexao.executaSql(sql);
        
         try {
             conexao.result.first();
             do{
                dados.add(new Object[]{conexao.result.getInt("idAluno"),conexao.result.getString("nomeAluno"), conexao.result.getDate("nascAluno")});  
             }while(conexao.result.next());
         } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,"Digite outro nome"+ex);
         }
         ModeloTabela modelo = new ModeloTabela(dados, colunas);
         
         JTableBuscar.setModel(modelo);
         JTableBuscar.getColumnModel().getColumn(0).setPreferredWidth(85);
         JTableBuscar.getColumnModel().getColumn(0).setResizable(false);
         JTableBuscar.getColumnModel().getColumn(1).setPreferredWidth(300);
         JTableBuscar.getColumnModel().getColumn(1).setResizable(false);
         JTableBuscar.getColumnModel().getColumn(2).setPreferredWidth(293);
         JTableBuscar.getColumnModel().getColumn(2).setResizable(false);
         JTableBuscar.getTableHeader().setReorderingAllowed(false);
         JTableBuscar.setAutoResizeMode(JTableBuscar.AUTO_RESIZE_OFF);
         JTableBuscar.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
         conexao.desconecta();  
    }
    
    public void preencherTabelaTurmas(String sql){
             ArrayList dados = new ArrayList();
        String [] colunas = new String[]{"Codigo", "Turma"};
        conexao.conexao();
        conexao.executaSql(sql);
        
         try {
             conexao.result.first();
             do{
                dados.add(new Object[]{conexao.result.getInt("idTurmas"),conexao.result.getString("nomeTurmaS")});  
             }while(conexao.result.next());
         } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,"Digite outro nome"+ex);
         }
         ModeloTabela modelo = new ModeloTabela(dados, colunas);
         
         JTableBuscar.setModel(modelo);
         JTableBuscar.getColumnModel().getColumn(0).setPreferredWidth(85);
         JTableBuscar.getColumnModel().getColumn(0).setResizable(false);
         JTableBuscar.getColumnModel().getColumn(1).setPreferredWidth(600);
         JTableBuscar.getColumnModel().getColumn(1).setResizable(false);
         JTableBuscar.setAutoResizeMode(JTableBuscar.AUTO_RESIZE_OFF);
         JTableBuscar.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
         conexao.desconecta();  
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Matricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Matricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Matricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Matricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Matricula().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTableBuscar;
    private javax.swing.JTable JTableMatriculados;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextFieldCurso;
    private javax.swing.JTextField jTextFieldDataMatricula;
    private javax.swing.JTextField jTextFieldIdTurmas;
    private javax.swing.JTextField jTextFieldInicioCurso;
    private javax.swing.JTextField jTextFieldNasc;
    private javax.swing.JTextField jTextFieldNomeAluno;
    private javax.swing.JTextField jTextFieldNomeTurma;
    private javax.swing.JTextField jTextFieldNumMatricula;
    private javax.swing.JTextField jTextFieldProfessor;
    private javax.swing.JButton jbBuscarAluno;
    private javax.swing.JButton jbBuscarTurma;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbEditar;
    private javax.swing.JButton jbExcluir;
    private javax.swing.JButton jbSalvar;
    // End of variables declaration//GEN-END:variables
}
